# Generated by Django 5.2 on 2025-06-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0002_courses_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='video_id',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
